In [2]:
%load_ext autoreload
%autoreload 2

In [74]:
from utils import load_data, load_data_lol, preprocess_features
import numpy as np

In [78]:
adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask = load_data('cora')

the feature vectors of both labeled and unlabeled training instances : (1708, 1433)
 the feature vectors of the training instances as scipy.sparse.csr.csr_matrix object :(140, 1433)
 the feature vectors of the test instances as scipy.sparse.csr.csr_matrix object : (1000, 1433)

the labels for instances in ind.dataset_str.allx as numpy.ndarray object : (1708, 7)
 he one-hot labels of the test instances as numpy.ndarray object : (1000, 7)

train  range(0, 140)
val  range(140, 640)
test  1708 2707


In [79]:
type(adj), type(features), type(y_train)

(scipy.sparse.csr.csr_matrix, scipy.sparse.lil.lil_matrix, numpy.ndarray)

In [5]:
y_train.shape, y_val.shape, y_test.shape

((3327, 6), (3327, 6), (3327, 6))

In [6]:
proc_feats = preprocess_features(features)

C:\Users\alex\dev\gcn\gcn\utils.py:115: RuntimeWarning: divide by zero encountered in power
  r_inv = np.power(rowsum, -1).flatten()


In [10]:
adj.shape

(3327, 3327)

In [1]:
from utils import *

In [33]:
data_path =  '..\\..\\deep-learning-class-project\\data\\2020_LoL_esports_match_data_from_OraclesElixir_20201005.csv'
adj, features, y_train, y_val, y_test, train_mask, val_mask, test_mask = load_data_lol(data_path)

 
 Begin processing data... 



C:\Users\alex\dev\gcn\gcn\utils.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams['adj_team_idx'] = teams['team'].apply(lambda team: ordered_teams.index(team))
C:\Users\alex\dev\gcn\gcn\utils.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teams['adj_game_idx'] = teams['gameid'].apply(lambda game: ordered_games.index(game))
C:\Users\alex\dev\gcn\gcn\utils.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] =

[0 1 2 3 4 5 6 7 8 9]
 
 Data processed 



In [36]:
adj = np.ones((5,5))

In [37]:
adj

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
adj[:,-1]

array([1., 1., 1., 1., 1.])

In [39]:
adj[-1,:]

array([1., 1., 1., 1., 1.])

In [40]:
adj[:,0:len(adj)-1]

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
'2020,2019'.split(',')

['2020', '2019']